name: Pull Requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "stable"
    - name: Install Dependencies
      run: |
        yarn --verbose install
    - name: Run Production Build
      run: |
        yarn --verbose build
